[versions]
compile-sdk-version = 33
target-sdk-version = 33
min-sdk-version = 22
app-version-code = 1
app-version-name = "1.0.0"


[libraries]
# Put your libraries here! They can be local or remote
compile-sdk-version = 33